#+TITLE: Emacs VHDL Tools

[[https://github.com/csantosb/vhdl-tools/blob/master/LICENSE][file:http://img.shields.io/badge/license-GNU%20GPLv3-blue.svg]]
[[http://stable.melpa.org/#/vhdl-tools][file:http://stable.melpa.org/packages/vhdl-tools-badge.svg]]
[[http://melpa.org/#/vhdl-tools][file:http://melpa.org/packages/vhdl-tools-badge.svg]]

This project provides useful VHDL support for Emacs in terms of navigation.

* Table of Contents                                 :TOC:
:PROPERTIES:
:VISIBILITY: all
:END:

 - [[#about][About]]
 - [[#license][License]]

* About

[[https://csantosb.github.io/blog/2015/12/23/vhdl-tools/][Vhdl-tools]] provides a minor mode intended to be used under [[https://guest.iis.ee.ethz.ch/~zimmi/emacs/vhdl-mode.html][vhdl-mode]].
It adds specific functionality on top of [[https://github.com/leoliu/ggtags][ggtags]], [[http://batsov.com/projectile/][projectile]], [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Imenu.html][imenu]] and
[[https://github.com/tj64/outshine][outshine]] to ease navigating vhdl sources. It expects a working setup of
=ggtags=, completing it with

  - Jumping into instances
  - Jump to upper level
  - Searching for references
  - Link and headings management
  - Custom use of =imenu=
  - Custom =smartscan=
  - Org / vhdl coupling

* License

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
