* Table of Contents                                 :TOC:
:PROPERTIES:
:VISIBILITY: all
:END:

- [[#58][5.8]]
- [[#57][5.7]]
  - [[#relative-feature-implement][Relative feature: implement]]
  - [[#remove-ugly-line-from-vorg-files][Remove ugly line from =vOrg= files]]
  - [[#better-jump-to-src-after-tangling][Better jump to src after tangling]]
  - [[#jump-from-vorg-to-vorg][Jump from vorg to vorg]]
  - [[#include-here-imenu-related-functions][Include here imenu related functions]]
  - [[#this][This]]
  - [[#vhdl-tools-vorg-src-block-beautify][vhdl-tools-vorg-src-block-beautify]]
  - [[#use-org-babel-post-tangle-hook][Use 'org-babel-post-tangle-hook’]]
  - [[#document-relative-feature][Document relative feature]]
  - [[#document-verbose-variable][Document verbose variable]]
  - [[#document-vhdl-tools-vorg-jump-from-vorg-into-module][Document ’vhdl-tools-vorg-jump-from-vorg-into-module’]]
  - [[#document-publish-a-project][Document publish a project]]
  - [[#document-new-major-modes][Document new major modes]]

* 6.0

** TODO Jump from vorg to vorg

Similarly as jumping from vhdl to vhdl


* 5.8

** TODO Better jump to src after tangling

Currently only a search for the line at point. If several identical
lines, this won’t work.

* 5.7

** DONE Relative feature: implement
CLOSED: [2017-07-21 ven. 15:52]

- CLOSING NOTE

  Done starting from this [[orgit-rev:~/Projects/perso/vhdl-tools/::c48c3a1][commilt]]
  ----------------------------------------------------------------

Give a chance to store source code in different folders.

** DONE Remove ugly line from =vOrg= files
CLOSED: [2017-07-21 ven. 15:45]

- CLOSING NOTE

  Done in this [[orgit-rev:~/Projects/perso/vhdl-tools/::bb3e36d][commit]].

  ----------------------------------------------------------------

#+begin_src org :tangle no
  #+begin_src vhdl :prologue (vhdl-tools--prologue-header-argument)
#+end_src

Try something like

#+begin_src emacs-lisp :tangle no
  (add-hook 'vhdl-tools-vorg-mode-hook
            (lambda ()
              (when vhdl-tools-use-outshine
                (setq-local org-babel-default-header-args
                            (cons `(:prologue . ,(vhdl-tools--prologue-header-argument))
                                  (assq-delete-all :prologue org-babel-default-header-args))))))
#+end_src

Unfourtunately, this makes the same header appear on top of all blocks.
